services:

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql

  node:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  mysql_data:
